prefix          = "dev"
region          = "us-east-1"
image_tag       = "latest"
docker_host     = "tcp://192.168.0.1:2375"
docker_registry = "registry.dev.example.com"
docker_username = "devuser"
docker_password = "devpass"
